# Generated by Django 4.2.3 on 2023-09-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='book_images')),
                ('isbn', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(max_length=100)),
                ('book_no', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
