# Generated by Django 4.2.3 on 2023-09-02 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_borrowlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlist',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 8, 43, 35, 812873)),
        ),
    ]
